### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Frost199** [elishaukpong/Team-Incredible#80]
index.php does not currently support python3 for Linux os

**Comment by ajawu** [comment]
This will be handled on the server

**Comment by Raraku** [comment]
Try making sure it's python 2.7 friendly as you can't be sure what compiler will handle it. This can help with that https://repl.it/languages/python

**Comment by Frost199** [comment]
@Raraku There is currently no point in making it **python 2.7** friendly, as @ajawu said they will handle it on the server, and again have you checked every other script submitted? how many devs still write **python 2.7**, talk less of new people coming in to use python.

If you can show me a python file that supports both **2.7** and **3.x** without headache, please you can let me know, I am always willing to take a look at it

thanks, @ajawu for the response
